In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import string 
import nltk as nlp

In [20]:
fake= pd.read_csv("Fake.csv")

In [21]:
true=pd.read_csv("True.csv")

In [22]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [28]:
true.head()

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [30]:
true["text"] = true["text"].replace("(Reuters)","",regex=True)

In [25]:
fake['target']=0

In [26]:
true['target']=1

In [31]:
true.head(10)

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON () - The head of a conservative Rep...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON () - Transgender people will be all...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON () - The special counsel investigat...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON () - Trump campaign adviser George ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON () - President Donald Trump...,politicsNews,"December 29, 2017",1
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON () - The Whit...",politicsNews,"December 29, 2017",1
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla () - President Donald Tru...",politicsNews,"December 29, 2017",1
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
9,Alabama official to certify Senator-elect Jone...,WASHINGTON () - Alabama Secretary of State Joh...,politicsNews,"December 28, 2017",1

In [32]:
fake.head(10)

,title,text,subject,date,target
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [34]:
fake=fake.drop(['title','subject','date'], axis=1)

In [35]:
true=true.drop(['title','subject','date'], axis=1)

In [36]:
news=pd.concat([fake, true], axis=0)

In [38]:
news.tail()

                                                    text  target
21412  BRUSSELS () - NATO allies on Tuesday welcomed ...       1
21413  LONDON () - LexisNexis, a provider of legal, r...       1
21414  MINSK () - In the shadow of disused Soviet-era...       1
21415  MOSCOW () - Vatican Secretary of State Cardina...       1
21416  JAKARTA () - Indonesia will buy 11 Sukhoi figh...       1

In [39]:
news=news.sample(frac=1)

In [40]:
news.head()

                                                    text  target
7968   Anyone who has read the Bible knows that that ...       0
1466   WASHINGTON () - The United States will admit a...       1
19510  SEOUL () - South Korea approved a plan on Thur...       1
4796   Dr. Harold Bornstein has been practicing medic...       0
13930  ANKARA () - Turkish President Tayyip Erdogan a...       1

In [41]:
news.reset_index(inplace=True)

In [42]:
news.drop(['index'], axis=1, inplace=True)

In [43]:
news.head()

                                                text  target
0  Anyone who has read the Bible knows that that ...       0
1  WASHINGTON () - The United States will admit a...       1
2  SEOUL () - South Korea approved a plan on Thur...       1
3  Dr. Harold Bornstein has been practicing medic...       0
4  ANKARA () - Turkish President Tayyip Erdogan a...       1

In [44]:
def word(text):
    text=text.lower()
    text=re.sub('\.*?\[]','',text)
    text = re.sub('[()]','',text)
    text = re.sub('\\W',' ',text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    return text

<>:3: SyntaxWarning: invalid escape sequence '\.'
<>:6: SyntaxWarning: invalid escape sequence '\S'
<>:8: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\.'
<>:6: SyntaxWarning: invalid escape sequence '\S'
<>:8: SyntaxWarning: invalid escape sequence '\w'
/var/folders/zz/tz7yr7rs1cl2y022b2vb_0640000gn/T/ipykernel_79361/1361725828.py:3: SyntaxWarning: invalid escape sequence '\.'
  text=re.sub('\.*?\[]','',text)
/var/folders/zz/tz7yr7rs1cl2y022b2vb_0640000gn/T/ipykernel_79361/1361725828.py:6: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub('https?://\S+|www\.\S+', '', text)
/var/folders/zz/tz7yr7rs1cl2y022b2vb_0640000gn/T/ipykernel_79361/1361725828.py:8: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub('\w*\d\w*', '', text)

In [45]:
news['text']= news['text'].apply(word)

In [47]:
news.head(50)

                                                 text  target
0   anyone who has read the bible knows that that ...       0
1   washington    the united states will admit a m...       1
2   seoul    south korea approved a plan on thursd...       1
3   dr  harold bornstein has been practicing medic...       0
4   ankara    turkish president tayyip erdogan and...       1
5   of course tomorrow morning  the democrat party...       0
6   london    myanmar is facing a  defining moment...       1
7   dubai    iranian president hassan rouhani said...       1
8    no one man can terrorize a whole nation unles...       0
9   knowing that hardworking americans need to be ...       0
10  washington    president donald trump said on t...       1
11  this one sentence should scare every taxpaying...       0
12  phnom penh    cambodia police on saturday depo...       1
13  the florida department of juvenile justice has...       0
14  beirut    the u s  backed syrian democratic fo...       1
15  police have identified duncan lloyd as the sus...       0
16  geneva    syria is in the throes of its worst ...       1
17  on saturday  former pennsylvania senator harri...       0
18  united nations    united nations secretary gen...       1
19  this ex ice agent reminds us of how ridiculous...       0
20  it s hard to read stories like this without wo...       0
21  washington    two u s  senators on tuesday rea...       1
22   in this february  story  corrects in second p...       1
23  eric holder was the king of extortion from big...       0
24  as a mother of three young girls  if anything ...       0
25  what a great photo of president trump joined b...       0
26  moscow    the kremlin said on wednesday it hop...       1
27  why is this woman not in jail the evidence is ...       0
28  baghdad erbil  iraq    iraq s supreme federal ...       1
29  a high profile  anti mass migration member of ...       0
30  washington    u s  house democratic leader nan...       1
31  donald trump s doctor didn t follow standard m...       0
32  lima    a public prosecutor in peru is seeking...       1
33  like moths to a lamp bam the terror suspect wh...       0
34  moscow    russian president vladimir putin sai...       1
35  washington    u s  president donald trump has ...       1
36  tomi lahren recently told the hollywood report...       0
37  remember when colleges and university were one...       0
38  two years ago  cleveland  tenn   businessman a...       0
39  senator bob corker r tn has had enough of the ...       0
40  washington    u s  president donald trump told...       1
41  madrid    archaeologists in spain have unearth...       1
42  the turkish government has blocked access to w...       0
43  this woman s having trouble entering the walma...       0
44  kampala    foreign victims of an attack on aid...       1
45  how very bold of the white yahoo sports writer...       0
46  washington    the top republican and democrat ...       1
47  sarajevo    forensic experts began searching a...       1
48  this is possibly the most disturbing video we ...       0
49  an arkansas school was ordered to desegregate ...       0

In [66]:
X= news['text']
Y=news['target']

In [ ]:
X_train,x_test,Y_train,y_test = train_test_split(X,Y,test_size=0.25)

(33673,)

In [ ]:
X_train.shape

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [70]:
vectorization = TfidfVectorizer()

In [71]:
analyze = vectorization.build_analyzer()

In [72]:
xv_train = vectorization.fit_transform(X_train)
xv_test = vectorization.transform(x_test)

In [73]:
print(xv_train.shape)
print(xv_test.shape)

(33673, 95842)
(11225, 95842)

In [74]:
from sklearn.linear_model import LogisticRegression

In [75]:
lr=LogisticRegression()

In [76]:
lr.fit(xv_train, Y_train)

LogisticRegression()

In [77]:
print("Accuracy:- ", lr.score(xv_test, y_test))

Accuracy:-  0.9832516703786192

In [78]:
from sklearn.metrics import classification_report

In [79]:
print(classification_report(y_test, lr.predict(xv_test)))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      5905
           1       0.98      0.98      0.98      5320

    accuracy                           0.98     11225
   macro avg       0.98      0.98      0.98     11225
weighted avg       0.98      0.98      0.98     11225

In [80]:
from sklearn.tree import DecisionTreeClassifier

In [81]:
dtc=DecisionTreeClassifier()

In [82]:
dtc.fit(xv_train, Y_train)

DecisionTreeClassifier()

In [83]:
print("Accuracy:- ", dtc.score(xv_test, y_test))

Accuracy:-  0.9507349665924276

In [84]:
print(classification_report(y_test, dtc.predict(xv_test)))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      5905
           1       0.96      0.94      0.95      5320

    accuracy                           0.95     11225
   macro avg       0.95      0.95      0.95     11225
weighted avg       0.95      0.95      0.95     11225

In [85]:
from sklearn.ensemble import GradientBoostingClassifier

In [86]:
gbc=GradientBoostingClassifier()

In [87]:
gbc.fit(xv_train, Y_train)

GradientBoostingClassifier()

In [88]:
print("Accuracy:- ", gbc.score(xv_test, y_test))

Accuracy:-  0.9717594654788418

In [89]:
print(classification_report(y_test, gbc.predict(xv_test)))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97      5905
           1       0.97      0.97      0.97      5320

    accuracy                           0.97     11225
   macro avg       0.97      0.97      0.97     11225
weighted avg       0.97      0.97      0.97     11225

In [90]:
from sklearn.ensemble import RandomForestClassifier

In [91]:
rfc=RandomForestClassifier()

In [92]:
rfc.fit(xv_train, Y_train)

RandomForestClassifier()

In [93]:
print("Accuracy:- ", rfc.score(xv_test, y_test))

Accuracy:-  0.9806681514476615

In [95]:
print(classification_report(y_test, rfc.predict(xv_test)))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      5905
           1       0.98      0.98      0.98      5320

    accuracy                           0.98     11225
   macro avg       0.98      0.98      0.98     11225
weighted avg       0.98      0.98      0.98     11225

In [96]:
def output(n):
    if n==0:
        return "Fake news"
    elif n==1:
        return "Not Fake news"

In [101]:
def testing(news):
    test_news= {"text":[news]}
    new_test= pd.DataFrame(test_news)
    new_test['text'] = new_test['text'].apply(word)
    new_x_test= new_test['text']
    new_xv_test= vectorization.transform(new_x_test)
    LR=lr.predict(new_xv_test)
    DTC=dtc.predict(new_xv_test)
    GBC=gbc.predict(new_xv_test)
    RFC=rfc.predict(new_xv_test)

    return print("\n\nLR Prediction: {} \nDT Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(output(LR[0]),output(DTC[0]),output(GBC[0]),output(RFC[0])))

In [103]:
news=str(input())
testing(news)

LR Prediction: Fake news
DT Prediction: Fake news
GBC Prediction: Fake news
RFC Prediction: Fake news